Insert into AHM.COUNTRY (ID,CITY,CODE) values (76,'French Polynesia','PF');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (77,'French Southern Territories','TF');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (78,'Gabon','GA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (79,'Gambia','GM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (80,'Georgia','GE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (81,'Germany','DE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (82,'Ghana','GH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (83,'Gibraltar','GI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (84,'Greece','GR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (85,'Greenland','GL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (86,'Grenada','GD');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (87,'Guadeloupe','GP');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (88,'Guam','GU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (89,'Guatemala','GT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (90,'Guinea','GN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (91,'Guinea-Bissau','GW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (92,'Guyana','GY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (93,'Haiti','HT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (94,'Heard Island and McDonald Islands','HM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (95,'Honduras','HN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (96,'Hong Kong','HK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (97,'Hungary','HU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (98,'Iceland','IS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (99,'India','IN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (100,'Indonesia','ID');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (101,'Iran (Islamic Republic of)','IR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (102,'Iraq','IQ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (103,'Ireland','IE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (104,'Israel','IL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (105,'Italy','IT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (106,'Jamaica','JM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (107,'Japan','JP');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (108,'Jordan','JO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (109,'Kazakhstan','KZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (110,'Kenya','KE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (111,'Kiribati','KI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (112,'Korea, Democratic People''s Republic of','KP');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (113,'Korea, Republic of','KR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (114,'Kuwait','KW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (115,'Kyrgyzstan','KG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (116,'Lao People''s Democratic Republic','LA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (117,'Latin America','LT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (118,'Latvia','LV');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (119,'Lebanon','LB');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (120,'Lesotho','LS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (121,'Liberia','LR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (122,'Libyan Arab Jamahiriya','LY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (123,'Liechtenstein','LI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (124,'Lithuania','LX');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (125,'Luxembourg','LU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (126,'Macau','MO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (127,'Macedonia','MK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (128,'Madagascar','MG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (129,'Malawi','MW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (130,'Malaysia','MY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (131,'Maldives','MV');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (132,'Mali','ML');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (133,'Malta','MT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (134,'Marshall Islands','MH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (135,'Martinique','MQ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (136,'Mauritania','MR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (137,'Mauritius','MU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (138,'Mayotte','YT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (139,'Mexico','MX');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (140,'Micronesia (Federated States of)','FM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (141,'Moldova, Republic of','MD');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (142,'Monaco','MC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (143,'Mongolia','MN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (144,'Montserrat','MS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (145,'Morocco','MA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (146,'Mozambique','MZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (147,'Myanmar','MM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (148,'Namibia','NA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (149,'Nauru','NR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (150,'Nepal','NP');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (151,'Netherlands','NL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (152,'Netherlands Antilles','AN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (153,'New Caledonia','NC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (154,'New Zealand','NZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (155,'Nicaragua','NI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (156,'Niger','NE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (157,'Nigeria','NG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (158,'Niue','NU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (159,'Norfolk Island','NF');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (160,'Northern Mariana Islands','MP');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (161,'Norway','NO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (162,'Oman','OM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (163,'Pakistan','PK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (164,'Palau','PW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (165,'Panama','PA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (166,'Papua New Guinea','PG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (167,'Paraguay','PY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (168,'Peru','PE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (169,'Philippines','PH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (170,'Pitcairn','PN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (171,'Poland','PL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (172,'Portugal','PT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (173,'Puerto Rico','PR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (174,'Qatar','QA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (175,'Reunion','RE');
commit;
Insert into AHM.COUNTRY (ID,CITY,CODE) values (176,'Romania','RO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (177,'Russian Federation','RU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (178,'Rwanda','RW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (179,'Saint Helena','SH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (180,'Saint Kitts and Nevis','KN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (181,'Saint Lucia','LC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (182,'Saint Pierre and Miquelon','PM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (183,'Saint Vincent and the Grenadines','VC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (184,'Samoa','WS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (185,'San Marino','SM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (186,'Sao Tome and Principe','ST');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (187,'Saudi Arabia','SA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (188,'Senegal','SN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (189,'Seychelles','SC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (190,'Sierra Leone','SL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (191,'Singapore','SG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (192,'Slovakia','SK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (193,'Slovenia','SI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (194,'Solomon Islands','SB');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (195,'Somalia','SO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (196,'South Africa','ZA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (197,'South Georgia and the South Sandwich Island','GS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (198,'Spain','ES');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (199,'Sri Lanka','LK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (200,'Sudan','SD');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (201,'Suriname','SR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (202,'Svalbard and Jan Mayen Islands','SJ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (203,'Swaziland','SZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (204,'Sweden','SE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (205,'Switzerland','CH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (206,'Syrian Arab Republic','SY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (207,'Taiwan','TW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (208,'Tajikistan','TJ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (209,'Tanzania, United Republic of','TZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (210,'Thailand','TH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (211,'Togo','TG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (212,'Tokelau','TK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (213,'Tonga','TO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (214,'Trinidad and Tobago','TT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (215,'Tunisia','TN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (216,'Turkey','TR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (217,'Turkmenistan','TM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (218,'Turks and Caicos Islands','TC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (219,'Tuvalu','TV');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (220,'Uganda','UG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (221,'Ukraine','UA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (222,'United Arab Emirates','AE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (223,'United Kingdom','GB');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (224,'United States','US');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (225,'United States Minor Outlying Islands','UM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (226,'Uruguay','UY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (227,'Uzbekistan','UZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (228,'Vanuatu','VU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (229,'Vatican City State (Holy See)','VA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (230,'Venezuela','VE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (231,'Viet Nam','VN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (232,'Virgin Islands (British)','VG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (233,'Virgin Islands (U.S.)','VI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (234,'Wallis and Futuna Islands','WF');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (235,'Western Sahara','EH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (236,'Yemen','YE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (237,'Yugoslavia','YU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (238,'Zaire','ZR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (239,'Zambia','ZM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (240,'Zimbabwe','ZW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (241,'YANGON','YGN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (1,'Afghanistan','AF');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (2,'Albania','AL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (3,'Algeria','DZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (4,'American Samoa','AS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (5,'Andorra','AD');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (6,'Angola','AO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (7,'Anguilla','AI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (8,'Antarctica','AQ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (9,'Antigua and Barbuda','AG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (10,'Argentina','AR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (11,'Armenia','AM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (12,'Aruba','AW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (13,'Australia','AU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (14,'Austria','AT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (15,'Azerbaijan','AZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (16,'Bahamas','BS');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (17,'Bahrain','BH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (18,'Bangladesh','BD');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (19,'Barbados','BB');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (20,'Belarus','BY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (21,'Belgium','BE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (22,'Belize','BZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (23,'Benin','BJ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (24,'Bermuda','BM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (25,'Bhutan','BT');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (26,'Bolivia','BO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (27,'Bosnia and Herzegovina','BA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (28,'Botswana','BW');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (29,'Bouvet Island','BV');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (30,'Brazil','BR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (31,'British Indian Ocean Territory','IO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (32,'Brunei Darussalam','BN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (33,'Bulgaria','BG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (34,'Burkina Faso','BF');
commit;
Insert into AHM.COUNTRY (ID,CITY,CODE) values (35,'Burundi','BI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (36,'Cambodia','KH');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (37,'Cameroon','CM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (38,'Canada','CA');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (39,'Cape Verde','CV');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (40,'Cayman Islands','KY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (41,'Central African Republic','CF');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (42,'Chad','TD');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (43,'Chile','CL');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (44,'China','CN');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (45,'Christmas Island','CX');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (46,'Cocos (Keeling) Islands','CC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (47,'Colombia','CO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (48,'Comoros','KM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (49,'Congo','CG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (50,'Cook Islands','CK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (51,'Costa Rica','CR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (52,'Cote d''Ivoire','CI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (53,'Croatia','HR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (54,'Cuba','CU');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (55,'Cyprus','CY');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (56,'Czech Republic','CZ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (57,'Denmark','DK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (58,'Djibouti','DJ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (59,'Dominica','DM');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (60,'Dominican Republic','DO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (61,'East Timor','TP');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (62,'Ecuador','EC');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (63,'Egypt','EG');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (64,'El Salvador','SV');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (65,'Equatorial Guinea','GQ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (66,'Eritrea','ER');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (67,'Estonia','EE');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (68,'Ethiopia','ET');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (69,'Falkland Islands (Malvinas)','FK');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (70,'Faroe Islands','FO');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (71,'Fiji','FJ');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (72,'Finland','FI');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (73,'France','FR');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (74,'France, Metropolitan','FX');
Insert into AHM.COUNTRY (ID,CITY,CODE) values (75,'French Guiana','GF');
commit;