INSERT INTO COUNTRY (Id,CITY,CODE)
    SELECT
       COUNTRYSEQ.NEXTVAL As Id,
       COUNTRY_NAME AS CITY,
       COUNTRY_ID AS CODE
    FROM APEX_030200.wwv_flow_countries;
    
    INSERT INTO BUSINESSTYPEAID(Id,BUSINESSTYPE) values ("1","GOLD");